<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>InfernalInkSteelSuite</RootNamespace>
    <AssemblyName>Infernal-Ink-Steel-Suite</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InfernalInkSteelSuite.Data\InfernalInkSteelSuite.Data.csproj" />
    <ProjectReference Include="..\InfernalInkSteelSuite.Domain\InfernalInkSteelSuite.Domain.csproj" />
    <ProjectReference Include="..\InfernalInkSteelSuite.Repositories\InfernalInkSteelSuite.Repositories.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.6" />

    <PackageReference Include="OpenTK.Audio.OpenAL" Version="4.9.4" />
    <PackageReference Include="ScottPlot.WPF" Version="5.1.57" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.0" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="shop_manager.db" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\eye_open.png" />
    <Resource Include="Assets\Images\eye_closed.png" />
  </ItemGroup>
</Project>
